### PR TITLE
Gov.bc.ca Script and test html

### PR DESCRIPTION
**Pull request by ryrjanes**
I have updated the gov.bc.ca script to include the node id context, this will be used by the cms lite dev team, currently only connects to snowplow mini for testing.  There is an html page to that I used for testing the new context. Also there is an html test page that is for multiple context of the same name, this will be used to ask snowplow about expected behavior.

### CODE REVIEW

**Comment by ryrjanes** [comment]
This is the set of updates and tests for the node id context. When approved I will be using this for the cms lite dev team

**Comment by danpollock** [comment]
If you are updating another example (the html example) you need to update it's readme to explain the files in there. Include in the instructions or html what the files are for and what a "multi context" example is all about. 

It needs to be clear to someone who lands in Github what it's all about. They won't have external context. 

Also, the URL is wrong: "examples/**gob.bc.ca**/README.md".

**Comment by ryrjanes** [comment]
I will fix the read me file to explain that example, also how do I go about fixing the folder name?

**Comment by danpollock** [comment]
No, the page doesn't make sense as it's written now. 

Now it looks like it's just about the multi example.

**Comment by danpollock** [comment]
@ryrjanes : When you get a chance, can you clean up examples/html_example/README.md to make clear what the two HTML files are and how to use then, and remove the code with the broken example?

**Comment by danpollock** [comment]
I've made some edits and approved the pull request.

**Pull request merged**
