### PR TITLE
Initial myfs schemas

### PR DESCRIPTION
**Pull request by danpollock**
Here's the initial MyFS schema upload. More details will come later.

### CODE REVIEW

**Comment by BJenning** [comment]
So i relinted with iglu using the correct flags (--skip-checks description,rootObject) and it cleared up all but the following error:

```
~/igluctl lint --skip-checks description,rootObject ca.bc.gov.myfs/estimator/jsonschema/1-0-0
FAILURE: Schema [/Users/bjenning/GDX-Analytics/examples/schemas/ca.bc.gov.myfs/estimator/jsonschema/1-0-0] contains following errors: 
1. Optional field doesn't allow null type
TOTAL: 0 Schemas were successfully validated
TOTAL: 1 invalid Schemas were encountered
TOTAL: 1 errors were encountered
TOTAL: 0 warnings were encountered
```

**Comment by danpollock** [comment]
> So i relinted with iglu using the correct flags (--skip-checks description,rootObject) and it cleared up all but the following error:
> 
> ```
> ~/igluctl lint --skip-checks description,rootObject ca.bc.gov.myfs/estimator/jsonschema/1-0-0
> FAILURE: Schema [/Users/bjenning/GDX-Analytics/examples/schemas/ca.bc.gov.myfs/estimator/jsonschema/1-0-0] contains following errors: 
> 1. Optional field doesn't allow null type
> TOTAL: 0 Schemas were successfully validated
> TOTAL: 1 invalid Schemas were encountered
> TOTAL: 1 errors were encountered
> TOTAL: 0 warnings were encountered
> ```

I've made a fix. Thanks for catching that!

**Comment by danpollock** [comment]
@BJenning Can you complete the review?

**Comment by BJenning** [comment]
I've relinted ca.bc.gov.myfs/estimator/jsonschema/1-0-0 and encountered no errors. Approved.

**Pull request merged**
